### ISSUE TITLE
Stall command

### ISSUE THREAD

**Issue by 2a5A1Ghu1** [SeqSEE/Hera#22]
Add a command to allow tickets to go to archive with a time limit to auto close or to be manually close. This should allow the user who opened a ticket time to reopen the ticket before the ticket auto closes or is manually closed. This will make it so users can reopen an unresolved issue without cluttering up active tickets and not having to explain a deleted issue again. This would reflect the common opendesk and helpdesk closed with reopen options.

Although probably not the intent and out of scope for a discord system, but having a backend that logs ticket conversations so old issues can be read would help too.

**Comment by SeqSEE** [comment]
Let's call this command stall, and add configuration values for STALL_LIMIT which is an integer value of the time in seconds to allow a ticket to remain open and STALL_AUTOCLOSE which is a boolean and determines if the tickets will stall forever or will auto close.

**Comment by 2a5A1Ghu1** [comment]
LOL You could call it ghost busters too or even lasers. as long as it does something like described above...

**Comment by SeqSEE** [comment]
> LOL You could call it ghost busters too or even lasers. as long as it does something like described above...

I wanted to name it stall because there is already an archive command planned and stall clarifies that it is being stalled due to inactivity
